package com.mvno.intercept.transcription;

import com.mvno.intercept.filter.AiFilterService;
import com.mvno.intercept.subscriber.InterceptResponse;
import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.vosk.Model;
import org.vosk.Recognizer;

import java.io.File;
import java.io.FileInputStream;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicLong;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import java.nio.charset.StandardCharsets;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;

import jakarta.annotation.PreDestroy;

/**
 * Native Vosk Speech-to-Text (ASR) Engine Service
 * 
 * Performs offline speech-to-text (ASR) transcription directly within the JVM process using native
 * JNI C++ bindings (com.alphacephei:vosk:0.3.45).
 * 
 * Zero-Cloud Latency Architecture:
 * - Monitors /var/spool/rtpengine for WAV audio captures generated by RTPEngine during Voice Calls.
 * - Loads the Vosk language model (default /opt/vosk-model-en-us-0.22) into off-heap native memory.
 * - Executes background polling every 3000ms via @Scheduled task executor on Virtual Threads.
 * 
 * @author MVNO Core Engineering Team
 * @version 1.0.0
 */
@Service
public class NativeVoskService {

    private static final Logger logger = LoggerFactory.getLogger(NativeVoskService.class);
    private final String spoolDir;
    private final String modelPath;
    private final AiFilterService aiFilterService;
    private final Counter transcriptions;
    private final Counter decodeErrors;
    private final Counter classified;
    private final Counter blocked;
    private final Counter unavailable;
    private final AtomicInteger modelReady = new AtomicInteger(0);
    private final AtomicLong lastStandbyWarn = new AtomicLong(0);
    private final AtomicLong lastSpoolWarn = new AtomicLong(0);
    private Model voskModel;

    public NativeVoskService(
            @Value("${vosk.spool-dir:/var/spool/rtpengine}") final String spoolDir,
            @Value("${vosk.model-path:/opt/vosk-model-small-en-us-0.15}") final String modelPath,
            final AiFilterService aiFilterService,
            final MeterRegistry meterRegistry) {
        this.spoolDir = spoolDir;
        this.modelPath = modelPath;
        this.aiFilterService = aiFilterService;
        // Micrometer telemetry counters and gauge for Vosk ASR health monitoring
        this.transcriptions = meterRegistry.counter("mvno.vosk.transcriptions");
        this.decodeErrors = meterRegistry.counter("mvno.vosk.decode.errors");
        this.classified = meterRegistry.counter("mvno.vosk.classified");
        this.blocked = meterRegistry.counter("mvno.vosk.blocked");
        this.unavailable = meterRegistry.counter("mvno.vosk.unavailable");
        meterRegistry.gauge("mvno.vosk.model.ready", modelReady);
        initModel();
    }

    /**
     * Initializes the native C++ Vosk ASR model into off-heap memory via JNI bindings.
     */
    private void initModel() {
        try {
            final File mDir = new File(modelPath);
            if (mDir.exists()) {
                // Instantiates native C++ Model struct in off-heap memory
                this.voskModel = new Model(modelPath);
                modelReady.set(1); // Set Prometheus gauge ready state = 1
                logger.info("Native Vosk Java 21 ASR Model loaded successfully from {}", modelPath);
            } else {
                logger.warn("Vosk ASR model directory not found at {}. Native Java ASR standby mode.", modelPath);
            }
        } catch (final Exception e) {
            logger.error("Failed to load native Vosk ASR model inside Java 21 JVM: {}", e.getMessage());
        }
    }

    /**
     * Spring Bean destruction hook: ensures native off-heap Vosk C++ memory is freed cleanly.
     */
    @PreDestroy
    public void destroyModel() {
        if (voskModel != null) {
            try {
                voskModel.close(); // Release JNI native pointers
                logger.info("Native Vosk JNI off-heap memory model resources closed successfully.");
            } catch (final Exception e) {
                logger.error("Error closing native Vosk ASR model: {}", e.getMessage());
            }
        }
    }

    /**
     * Decodes 16kHz mono WAV audio file in JVM memory and returns transcribed text string.
     * 
     * @param wavFile Target audio file captured by RTPEngine.
     * @return Transcribed text string extracted by Vosk ASR.
     */
    public String transcribeWav(final File wavFile) {
        if (voskModel == null) {
            return "Vosk model unavailable";
        }
        // Open WAV audio stream and create a Vosk Recognizer matching the audio sample rate
        try (final AudioInputStream ais = AudioSystem.getAudioInputStream(wavFile);
             final Recognizer recognizer = new Recognizer(voskModel, ais.getFormat().getSampleRate())) {
            
            // Read raw PCM audio stream in 4KB byte chunks and pass directly to JNI C++ recognizer
            final byte[] buffer = new byte[4096];
            int bytesRead;
            while ((bytesRead = ais.read(buffer)) >= 0) {
                recognizer.acceptWaveForm(buffer, bytesRead);
            }
            transcriptions.increment(); // Increment Micrometer transcription metric
            return recognizer.getResult(); // Return JSON string containing transcribed text
        } catch (final Exception e) {
            decodeErrors.increment();
            logger.error("Native Java 21 Vosk ASR decoding error: {}", e.getMessage());
            return "";
        }
    }

    /**
     * Routes a transcribed recording to the AI filter and records the verdict counters.
     * Post-call analytics only — a failure is logged and never stalls the spool loop.
     *
     * @param fileName Spool WAV filename (recording identifier = stem, no SIP Call-ID).
     * @param text     Vosk ASR transcript text; blank transcripts are skipped.
     */
    void classifyAndRecord(final String fileName, final String text) {
        if (text.isBlank()) {
            logger.warn("Skipping AI classification for [{}]: empty transcript", fileName);
            return;
        }
        try {
            final String recordingId = fileName.replaceAll("(?i)\\.wav$", "");
            final InterceptResponse verdict = aiFilterService.classifyTranscript(recordingId, text);
            classified.increment();
            if (!verdict.allow()) {
                blocked.increment();
            }
            logger.info("AI transcript verdict [{}]: allow={}, reason='{}'",
                    recordingId, verdict.allow(), verdict.reason());
        } catch (final Exception e) {
            logger.error("AI transcript classification error [{}]: {}", fileName, e.getMessage());
        }
    }

    /**
     * Periodically polls media spool directory on Virtual Threads every 3000ms to process new audio captures.
     */
    @Scheduled(fixedDelay = 3000)
    public void pollSpoolDirectory() {
        if (voskModel == null) {
            // Fail-open: calls proceed; transcription is best-effort post-call analytics.
            // Visible marker (throttled) so operators know ASR is unavailable.
            unavailable.increment();
            final long now = System.currentTimeMillis();
            if (now - lastStandbyWarn.get() > 60_000) {
                lastStandbyWarn.set(now);
                logger.warn("TRANSCRIPTION UNAVAILABLE: Vosk ASR model not loaded - calls proceed, transcription skipped (mvno.vosk.unavailable={})", unavailable.count());
            }
            return;
        }
        try {
            final Path spoolPath = Paths.get(spoolDir);
            if (!Files.exists(spoolPath)) {
                final long now = System.currentTimeMillis();
                if (now - lastSpoolWarn.get() > 60_000) {
                    lastSpoolWarn.set(now);
                    logger.warn("RECORDING SPOOL MISSING: {} not found - no recordings to transcribe (fail-open, calls unaffected)", spoolDir);
                }
                return;
            }

            // Filter for .wav files in RTPEngine spool directory
            try (final DirectoryStream<Path> stream = Files.newDirectoryStream(spoolPath, entry -> {
                String name = entry.getFileName().toString().toLowerCase();
                return name.endsWith(".wav");
            })) {
                // Ensure 'archived' subdirectory exists for processed audio files
                final Path archiveDir = spoolPath.resolve("archived");
                if (!Files.exists(archiveDir)) {
                    Files.createDirectories(archiveDir);
                }
                
                // Process each .wav file that has finished writing (file age > 3000ms)
                for (final Path path : stream) {
                    final File file = path.toFile();
                    if (!file.isDirectory() && System.currentTimeMillis() - file.lastModified() > 3000) {
                        // Transcribe WAV audio to text
                        final String text = transcribeWav(file);
                        logger.info("Native Java 21 Vosk ASR Transcribed [{}]: {}", file.getName(), text);

                        // Save text transcription file (.txt) alongside archived WAV audio
                        try {
                            final String txtFileName = file.getName().replaceAll("(?i)\\.wav$", ".txt");
                            Files.writeString(archiveDir.resolve(txtFileName), text, StandardCharsets.UTF_8);
                        } catch (final Exception e) {
                            logger.error("Failed writing transcription txt file: {}", e.getMessage());
                        }

                        // Route transcript to the AI filter for post-call scam/spam verdict.
                        // rtpengine spool names carry no SIP Call-ID (call-<epoch>%<host>-<hash>.wav),
                        // so the filename stem is used as the recording identifier.
                        classifyAndRecord(file.getName(), text);
                        
                        // Move processed audio file to 'archived' directory
                        Files.move(path, archiveDir.resolve(path.getFileName()), StandardCopyOption.REPLACE_EXISTING);
                    }
                }
            }
        } catch (final Exception e) {
            logger.error("Spool directory polling error: {}", e.getMessage());
        }
    }
}
