package com.mvno.intercept.transcription;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.vosk.Model;
import org.vosk.Recognizer;

import java.io.File;
import java.io.FileInputStream;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * <h1>Native Vosk Speech-to-Text (ASR) Engine Service</h1>
 * 
 * <p>The {@code NativeVoskService} performs offline speech-to-text (ASR) transcription directly within the
 * Java 21 Virtual Machine process using native JNI C++ bindings ({@code com.alphacephei:vosk:0.3.45}).</p>
 * 
 * <h2>Architecture &amp; Zero-Cloud Latency</h2>
 * <p>Eliminates external cloud API dependencies (like Google Cloud Speech or OpenAI Whisper) by executing
 * offline acoustic decoding locally inside JVM native memory:</p>
 * <ul>
 *   <li><b>Media Spool Directory:</b> Monitors {@code /var/spool/rtpengine} for PCAP audio captures generated by RTPEngine during Voice Calls.</li>
 *   <li><b>Acoustic Model:</b> Loads lightweight Vosk language model ({@code /opt/vosk-model-small-en-us-0.15}) into off-heap native C++ memory.</li>
 *   <li><b>Virtual Thread Polling:</b> Executes background polling every 3000ms via Spring's {@link Scheduled @Scheduled} task executor on Virtual Threads.</li>
 * </ul>
 * 
 * <h2>PCM Decoding Pipeline</h2>
 * <ol>
 *   <li>Detects completed 16kHz mono WAV audio captures in spool directory.</li>
 *   <li>Streams raw 4096-byte PCM chunks to {@link Recognizer#acceptWaveForm(byte[], int)}.</li>
 *   <li>Extracts final text transcript string and cleans up processed audio spool files.</li>
 * </ol>
 * 
 * @author MVNO Core Engineering Team
 * @version 1.0.0
 * @see org.vosk.Model
 * @see org.vosk.Recognizer
 */
@Service
public class NativeVoskService {

    private static final Logger logger = LoggerFactory.getLogger(NativeVoskService.class);

    /** Target media spool directory path (property: {@code vosk.spool-dir}). Default: {@code /var/spool/rtpengine}. */
    private final String spoolDir;

    /** Model directory path (property: {@code vosk.model-path}). Default: {@code /opt/vosk-model-small-en-us-0.15}. */
    private final String modelPath;

    /** Native JNI Vosk C++ Model pointer instance. */
    private Model voskModel;

    /**
     * Constructs the Native Vosk ASR Service and triggers offline acoustic model loading.
     * 
     * @param spoolDir Spool directory path where RTPEngine writes PCAP audio captures.
     * @param modelPath File system path to the extracted Vosk language model directory.
     */
    public NativeVoskService(
            @Value("${vosk.spool-dir:/var/spool/rtpengine}") final String spoolDir,
            @Value("${vosk.model-path:/opt/vosk-model-small-en-us-0.15}") final String modelPath) {
        this.spoolDir = spoolDir;
        this.modelPath = modelPath;
        initModel();
    }

    /**
     * Initializes the native C++ Vosk Model instance within JVM native memory.
     */
    private void initModel() {
        try {
            final File mDir = new File(modelPath);
            if (mDir.exists()) {
                this.voskModel = new Model(modelPath);
                logger.info("Native Vosk Java 21 ASR Model loaded successfully from {}", modelPath);
            } else {
                logger.warn("Vosk ASR model directory not found at {}. Native Java ASR standby mode.", modelPath);
            }
        } catch (final Exception e) {
            logger.error("Failed to load native Vosk ASR model inside Java 21 JVM: {}", e.getMessage());
        }
    }

    /**
     * Decodes a 16kHz mono WAV audio file directly in Java memory space and returns the transcribed text string.
     * 
     * @param wavFile Target audio file.
     * @return Transcribed text string produced by the acoustic recognizer.
     */
    public String transcribeWav(final File wavFile) {
        if (voskModel == null) {
            return "Vosk model unavailable";
        }
        try (final FileInputStream fis = new FileInputStream(wavFile);
             final Recognizer recognizer = new Recognizer(voskModel, 16000)) {
            
            final byte[] buffer = new byte[4096];
            int bytesRead;
            while ((bytesRead = fis.read(buffer)) >= 0) {
                recognizer.acceptWaveForm(buffer, bytesRead);
            }
            return recognizer.getResult();
        } catch (final Exception e) {
            logger.error("Native Java 21 Vosk ASR decoding error: {}", e.getMessage());
            return "";
        }
    }

    /**
     * Periodically polls the media spool directory on Virtual Threads every 3000ms to process new audio captures.
     */
    @Scheduled(fixedDelay = 3000)
    public void pollSpoolDirectory() {
        if (voskModel == null) {
            return;
        }
        try {
            final Path spoolPath = Paths.get(spoolDir);
            if (!Files.exists(spoolPath)) {
                return;
            }

            try (final DirectoryStream<Path> stream = Files.newDirectoryStream(spoolPath, "*.wav")) {
                for (final Path path : stream) {
                    final File file = path.toFile();
                    // Process files modified more than 3 seconds ago to ensure file write completion
                    if (System.currentTimeMillis() - file.lastModified() > 3000) {
                        final String text = transcribeWav(file);
                        logger.info("Native Java 21 Vosk ASR Transcribed [{}]: {}", file.getName(), text);
                        Files.deleteIfExists(path);
                    }
                }
            }
        } catch (final Exception e) {
            logger.error("Spool directory polling error: {}", e.getMessage());
        }
    }
}
