package com.mvno.intercept.transcription;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.vosk.Model;
import org.vosk.Recognizer;

import java.io.File;
import java.io.FileInputStream;
import java.nio.file.DirectoryStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 * Native Vosk Speech-to-Text (ASR) Engine Service
 * 
 * Performs offline speech-to-text (ASR) transcription directly within the JVM process using native
 * JNI C++ bindings (com.alphacephei:vosk:0.3.45).
 * 
 * Zero-Cloud Latency Architecture:
 * - Monitors /var/spool/rtpengine for PCAP audio captures generated by RTPEngine during Voice Calls.
 * - Loads lightweight Vosk language model (/opt/vosk-model-small-en-us-0.15) into off-heap native memory.
 * - Executes background polling every 3000ms via @Scheduled task executor on Virtual Threads.
 * 
 * @author MVNO Core Engineering Team
 * @version 1.0.0
 */
@Service
public class NativeVoskService {

    private static final Logger logger = LoggerFactory.getLogger(NativeVoskService.class);
    private final String spoolDir;
    private final String modelPath;
    private Model voskModel;

    public NativeVoskService(
            @Value("${vosk.spool-dir:/var/spool/rtpengine}") final String spoolDir,
            @Value("${vosk.model-path:/opt/vosk-model-small-en-us-0.15}") final String modelPath) {
        this.spoolDir = spoolDir;
        this.modelPath = modelPath;
        initModel();
    }

    private void initModel() {
        try {
            final File mDir = new File(modelPath);
            if (mDir.exists()) {
                this.voskModel = new Model(modelPath);
                logger.info("Native Vosk Java 21 ASR Model loaded successfully from {}", modelPath);
            } else {
                logger.warn("Vosk ASR model directory not found at {}. Native Java ASR standby mode.", modelPath);
            }
        } catch (final Exception e) {
            logger.error("Failed to load native Vosk ASR model inside Java 21 JVM: {}", e.getMessage());
        }
    }

    /**
     * Decodes 16kHz mono WAV audio file in JVM memory and returns transcribed text string.
     * 
     * @param wavFile Target audio file.
     * @return Transcribed text string.
     */
    public String transcribeWav(final File wavFile) {
        if (voskModel == null) {
            return "Vosk model unavailable";
        }
        try (final FileInputStream fis = new FileInputStream(wavFile);
             final Recognizer recognizer = new Recognizer(voskModel, 16000)) {
            
            final byte[] buffer = new byte[4096];
            int bytesRead;
            while ((bytesRead = fis.read(buffer)) >= 0) {
                recognizer.acceptWaveForm(buffer, bytesRead);
            }
            return recognizer.getResult();
        } catch (final Exception e) {
            logger.error("Native Java 21 Vosk ASR decoding error: {}", e.getMessage());
            return "";
        }
    }

    /**
     * Periodically polls media spool directory on Virtual Threads every 3000ms to process new audio captures.
     */
    @Scheduled(fixedDelay = 3000)
    public void pollSpoolDirectory() {
        if (voskModel == null) {
            return;
        }
        try {
            final Path spoolPath = Paths.get(spoolDir);
            if (!Files.exists(spoolPath)) {
                return;
            }

            try (final DirectoryStream<Path> stream = Files.newDirectoryStream(spoolPath, "*.wav")) {
                for (final Path path : stream) {
                    final File file = path.toFile();
                    if (System.currentTimeMillis() - file.lastModified() > 3000) {
                        final String text = transcribeWav(file);
                        logger.info("Native Java 21 Vosk ASR Transcribed [{}]: {}", file.getName(), text);
                        Files.deleteIfExists(path);
                    }
                }
            }
        } catch (final Exception e) {
            logger.error("Spool directory polling error: {}", e.getMessage());
        }
    }
}
