logger:
  file:
    path: /var/log/open5gs/bsf.log

default:
  no_tls: true

global:
  max:
    ue: 1024

bsf:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7777
        no_tls: true
        advertise: bsf
    client:
      nrf:
        - uri: http://nrf:7777
          no_tls: true
