FROM node:20-alpine
WORKDIR /usr/src/app
RUN apk add --no-cache git python3 make g++
RUN git clone --depth 1 --branch v2.8.0 https://github.com/open5gs/open5gs.git /tmp/open5gs && \
    cp -r /tmp/open5gs/webui/* /usr/src/app/ && \
    rm -rf /tmp/open5gs
RUN npm install && \
    ln -s /usr/src/app/src/modules /usr/src/app/node_modules/modules && \
    ln -s /usr/src/app/src/containers /usr/src/app/node_modules/containers && \
    ln -s /usr/src/app/src/components /usr/src/app/node_modules/components && \
    ln -s /usr/src/app/src/helpers /usr/src/app/node_modules/helpers && \
    ln -s /usr/src/app/src/modules /usr/src/app/pages/modules && \
    ln -s /usr/src/app/src/containers /usr/src/app/pages/containers && \
    ln -s /usr/src/app/src/components /usr/src/app/pages/components && \
    ln -s /usr/src/app/src/helpers /usr/src/app/pages/helpers
EXPOSE 3000
ENV DB_URI=mongodb://mongodb:27017/open5gs
ENV HOST=0.0.0.0
ENV PORT=3000
ENV NODE_PATH=src
CMD ["node", "server/index.js"]
