logger:
  file:
    path: /var/log/open5gs/nssf.log

default:
  no_tls: true

global:
  max:
    ue: 1024

nssf:
  sbi:
    server:
      - address: 0.0.0.0
        port: 7777
        no_tls: true
        advertise: nssf
    client:
      nrf:
        - uri: http://nrf:7777
          no_tls: true
      nsi:
        - uri: http://nrf:7777
          s_nssai:
            sst: 1
